apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gin-fleamarket-db
  namespace: gin-fleamarket
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  instances: 1
  bootstrap:
    initdb:
      database: fleamarket
      owner: ginuser
      secret:
        name: gin-fleamarket-db-creds
  storage:
    size: 1Gi
    storageClass: openebs-hostpath
