apiVersion: v1
kind: Secret
metadata:
  name: gin-fleamarket-db-creds
  namespace: gin-fleamarket
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
type: kubernetes.io/basic-auth
stringData:
  username: ginuser
  password: ginpassword
---
apiVersion: v1
kind: Secret
metadata:
  name: gin-fleamarket-env
  namespace: gin-fleamarket
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
stringData:
  .env: |
    ENV=prod
    DB_HOST=gin-fleamarket-db-rw
    DB_PORT=5432
    DB_USER=ginuser
    DB_PASSWORD=ginpassword
    DB_NAME=fleamarket
    SECRET_KEY=your-secret-key-here
