repositories:
  - name: openebs
    url: https://openebs.github.io/openebs

releases:
  - name: openebs
    namespace: openebs
    createNamespace: true
    chart: openebs/openebs
    version: 4.2.0
    values:
      - values.yaml
