apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mastodon-redis-auth
  namespace: mastodon
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: mastodon-redis-auth
  data:
    - secretKey: redis-password
      remoteRef:
        key: mastodon-redis-password
