apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mastodon-redis
  namespace: mastodon
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon-redis
  namespace: mastodon
  labels:
    app: mastodon-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mastodon-redis
  template:
    metadata:
      labels:
        app: mastodon-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          command: ["sh", "-c", "redis-server --appendonly yes --requirepass $REDIS_PASSWORD"]
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mastodon-redis-auth
                  key: redis-password
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 256Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mastodon-redis
---
apiVersion: v1
kind: Service
metadata:
  name: mastodon-redis
  namespace: mastodon
spec:
  selector:
    app: mastodon-redis
  ports:
    - port: 6379
      targetPort: 6379
