apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-credentials
  namespace: cloudflare-tunnel-ingress-controller
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: cloudflare-credentials
  data:
    - secretKey: api_token
      remoteRef:
        key: cloudflare-api-token
    - secretKey: account_id
      remoteRef:
        key: cloudflare-account-id
    - secretKey: tunnel_name
      remoteRef:
        key: cloudflare-tunnel-name
