apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-tunnel-ingress-controller
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://helm.strrl.dev
      chart: cloudflare-tunnel-ingress-controller
      targetRevision: 0.0.22
      helm:
        valueFiles:
          - $values/addons/cloudflare-tunnel-ingress-controller/values.yaml
    - repoURL: git@github.com:kkato/k8s
      targetRevision: main
      ref: values
    - repoURL: git@github.com:kkato/k8s
      targetRevision: main
      path: addons/cloudflare-tunnel-ingress-controller
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflare-tunnel-ingress-controller
  ignoreDifferences:
    - group: external-secrets.io
      kind: ExternalSecret
      jsonPointers:
        - /spec/data/0/remoteRef/conversionStrategy
        - /spec/data/0/remoteRef/decodingStrategy
        - /spec/data/0/remoteRef/metadataPolicy
        - /spec/data/1/remoteRef/conversionStrategy
        - /spec/data/1/remoteRef/decodingStrategy
        - /spec/data/1/remoteRef/metadataPolicy
        - /spec/data/2/remoteRef/conversionStrategy
        - /spec/data/2/remoteRef/decodingStrategy
        - /spec/data/2/remoteRef/metadataPolicy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
