## ArgoCD custom values
configs:
  cm:
    accounts.admin: apiKey

server:
  ingress:
    enabled: true
    ingressClassName: cloudflare-tunnel
    hostname: argocd.kkato.app
    tls: false
    annotations: {}
  extraArgs:
    - --insecure
