apiVersion: v1
kind: Secret
metadata:
  name: todo-app-go-db-creds
  namespace: todo-app-go
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
type: kubernetes.io/basic-auth
stringData:
  username: todouser
  password: todopassword
---
apiVersion: v1
kind: Secret
metadata:
  name: todo-app-go-env
  namespace: todo-app-go
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
stringData:
  DATABASE_URL: postgres://todouser:todopassword@todo-app-go-db-rw:5432/todo
