apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-app-go
  namespace: todo-app-go
spec:
  ingressClassName: cloudflare-tunnel
  rules:
    - host: todo-app-go.kkato.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: todo-app-go
                port:
                  number: 80
