apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:kkato/k8s
    targetRevision: main
    path: apps/jellyfin/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: home-recorder
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
