apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mastodon-resources
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:kkato/k8s
    targetRevision: main
    path: apps/mastodon/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: mastodon
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true  # VPA CRD 導入前の sync でも失敗しないよう設定
